### ISSUE TITLE
Why does umami-python need for username and Password

### ISSUE THREAD

**Issue by ddxv** [mikeckennedy/umami-python#1]
Hello, awesome project, I've been thinking about something similar for several server applications I run for mobile apps or games, so I'm definitely looking forward to adding this.  

I didn't see a discussion section, so please let me know if there is somewhere better to move this conversation.

Why does umami-python need to use the login username and password for calling events? My limited Umami experience is that it is a small js snippet added to pages, which only contains my resource ID. 

Why would this need more information in order to authenticate?

**Comment by mikeckennedy** [comment]
Hi @ddxv. Good question. It needs auth because the API can do much more than just post events.

https://umami.is/docs/websites-api

For example, there you can create entire new websites to be tracked, or even delete the current one! 

However, your question got me thinking, how is the `create_new_event()` method different than a standard user via a web browser that doesn't have an account. It's not and that one method doesn't need auth. I drop the auth requirement for create_new_event() in the next release.

**Comment by mikeckennedy** [comment]
Done via [dfa4538](https://github.com/mikeckennedy/umami-python/commit/dfa4538b003fd8e4aa7d4a263ecdeb48f167ec03)

**Comment by ddxv** [comment]
Thanks!
